In [2]:
import numpy as np

In [5]:
arr = np.arange(1, 1000, 25)
arr

array([  1,  26,  51,  76, 101, 126, 151, 176, 201, 226, 251, 276, 301,
       326, 351, 376, 401, 426, 451, 476, 501, 526, 551, 576, 601, 626,
       651, 676, 701, 726, 751, 776, 801, 826, 851, 876, 901, 926, 951,
       976])

In [6]:
arr.shape

(40,)

In [8]:
arr.reshape(4,10)

array([[  1,  26,  51,  76, 101, 126, 151, 176, 201, 226],
       [251, 276, 301, 326, 351, 376, 401, 426, 451, 476],
       [501, 526, 551, 576, 601, 626, 651, 676, 701, 726],
       [751, 776, 801, 826, 851, 876, 901, 926, 951, 976]])

In [15]:
E = np.array([[[0, 0.5667, 0.5988, 0],
              [0.7502, 0,1.38,0],
              [0,0,0,0.64],
             [0,0,0.5229,0]],
              [[0,0.79,-1.55,0],
               [-0.5855,0,1.5863,0],
               [0,0,0,0.55],
               [0,0,2.3,0]]])

In [16]:
E

array([[[ 0.    ,  0.5667,  0.5988,  0.    ],
        [ 0.7502,  0.    ,  1.38  ,  0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.64  ],
        [ 0.    ,  0.    ,  0.5229,  0.    ]],

       [[ 0.    ,  0.79  , -1.55  ,  0.    ],
        [-0.5855,  0.    ,  1.5863,  0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.55  ],
        [ 0.    ,  0.    ,  2.3   ,  0.    ]]])

In [23]:
E = E

In [24]:
E.shape

(4, 4, 2)

In [28]:
E[:,:,0]

array([[0.    , 0.7502, 0.    , 0.    ],
       [0.5667, 0.    , 0.    , 0.    ],
       [0.5988, 1.38  , 0.    , 0.5229],
       [0.    , 0.    , 0.64  , 0.    ]])